version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elastic
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200 # for http
      - 9300:9300 # for tcp
    volumes:
      - esdata:/usr/share/elasticsearch/data

  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile-Dev
    container_name: web
    ports: 
      - 8080:8080
    volumes: 
      - ${PWD}/front-end/src:/app/src

  server:
    build: ./back-end
    container_name: server
    ports:
     - 3000:3000
    volumes:
      - ${PWD}/back-end/server:/app/server

volumes: 
  esdata:
