version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elastic
    environment: 
      discovery.type: single-node
    ports:
      - 9200:9200 # for http
      - 9300:9300 # for tcp
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: